#!/bin/bash
# Synchronize all submodules and update .gitmodules

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${PROJECT_ROOT}/scripts/lib/common.sh"

sync_submodules() {
    log_header "Synchronizing Submodules"
    
    cd "${PROJECT_ROOT}"
    
    # Generate .gitmodules from registry
    log_info "Regenerating .gitmodules..."
    
    echo "# Auto-generated by scripts/submodules/sync.sh" > .gitmodules
    echo "# Do not edit manually" >> .gitmodules
    echo "" >> .gitmodules
    
    # Add each repository as submodule
    yq eval '.repositories[]' "${PROJECT_ROOT}/registry/repositories.yaml" | \
    yq eval -o=json | jq -r '.full_name + "|" + .submodule_path + "|" + .github_url' | \
    while IFS='|' read -r full_name submodule_path github_url; do
        log_info "Configuring submodule: ${full_name}"
        
        cat >> .gitmodules << EOF
[submodule "${submodule_path}"]
    path = ${submodule_path}
    url = ${github_url}
    branch = main
EOF
        
        # Add submodule if not exists
        if [ ! -d "$submodule_path" ]; then
            git submodule add "${github_url}" "${submodule_path}" 2>/dev/null || true
        fi
    done
    
    # Initialize and update submodules
    log_info "Initializing submodules..."
    git submodule init
    
    log_info "Updating submodules..."
    git submodule update --remote --merge
    
    # Update registry with current versions
    log_info "Updating version registry..."
    
    for module in modules/*; do
        if [ -d "$module" ]; then
            repo_name=$(basename "$module")
            
            cd "$module"
            
            # Get current version from git tags
            current_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
            current_version=${current_version#v}
            
            # Update registry
            update_version "$repo_name" "$current_version"
            
            cd "${PROJECT_ROOT}"
        fi
    done
    
    log_success "Submodules synchronized"
}

# Main execution
main() {
    sync_submodules
    
    # Commit changes
    if ! git diff --quiet .gitmodules registry/; then
        git add .gitmodules registry/
        git commit -m "chore: synchronize submodules and registry

- Updated .gitmodules
- Synchronized versions in registry
- Updated submodule references"
        
        log_success "Changes committed"
    else
        log_info "No changes to commit"
    fi
}

main "$@"